/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE AVSS_PRS_SYS_STATUS PACKING
package io.mavlink.AVSSUAS;
import io.mavlink.MAVLinkPacket;
import io.mavlink.Messages.MAVLinkMessage;
import io.mavlink.Messages.MAVLinkPayload;
        
/**
 *  AVSS PRS system status.
 */
public class msg_avss_prs_sys_status extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS = 60050;
    public static final int MAVLINK_MSG_LENGTH = 12;
    private static final long serialVersionUID = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;

      
    /**
     * PRS error statuses
     */
    public long error_status;
      
    /**
     * Time since PRS system boot
     */
    public long time_boot_ms;
      
    /**
     * Estimated battery run-time without a remote connection and PRS battery voltage
     */
    public int battery_status;
      
    /**
     * PRS arm statuses
     */
    public short arm_status;
      
    /**
     * PRS battery change statuses
     */
    public short change_status;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;
        
        packet.payload.putUnsignedInt(error_status);
        packet.payload.putUnsignedInt(time_boot_ms);
        packet.payload.putUnsignedShort(battery_status);
        packet.payload.putUnsignedByte(arm_status);
        packet.payload.putUnsignedByte(change_status);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a avss_prs_sys_status message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.error_status = payload.getUnsignedInt();
        this.time_boot_ms = payload.getUnsignedInt();
        this.battery_status = payload.getUnsignedShort();
        this.arm_status = payload.getUnsignedByte();
        this.change_status = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_avss_prs_sys_status() {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_avss_prs_sys_status( long error_status, long time_boot_ms, int battery_status, short arm_status, short change_status) {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;

        this.error_status = error_status;
        this.time_boot_ms = time_boot_ms;
        this.battery_status = battery_status;
        this.arm_status = arm_status;
        this.change_status = change_status;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_avss_prs_sys_status( long error_status, long time_boot_ms, int battery_status, short arm_status, short change_status, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.error_status = error_status;
        this.time_boot_ms = time_boot_ms;
        this.battery_status = battery_status;
        this.arm_status = arm_status;
        this.change_status = change_status;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_avss_prs_sys_status(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS - sysid:"+sysid+" compid:"+compid+" error_status:"+error_status+" time_boot_ms:"+time_boot_ms+" battery_status:"+battery_status+" arm_status:"+arm_status+" change_status:"+change_status+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS";
    }
}
        