/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package io.mavlink.enums;

/** 
 * Types of airspeed sensor/data. May be be used in AIRSPEED message to estimate accuracy of indicated speed.
 */
public class AIRSPEED_SENSOR_TYPE {
   public static final int AIRSPEED_SENSOR_TYPE_UNKNOWN = 0; /* Airspeed sensor type unknown/not supplied. | */
   public static final int AIRSPEED_SENSOR_TYPE_DIFFERENTIAL = 1; /* Differential airspeed sensor | */
   public static final int AIRSPEED_SENSOR_TYPE_MASS_FLOW = 2; /* Mass-flow airspeed sensor. | */
   public static final int AIRSPEED_SENSOR_TYPE_WINDVANE = 3; /* Windvane airspeed sensor. | */
   public static final int AIRSPEED_SENSOR_TYPE_SYNTHETIC = 4; /* Synthetic/calculated airspeed. | */
   public static final int AIRSPEED_SENSOR_TYPE_ENUM_END = 5; /*  | */
}
            